version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game
      PGDATA: /data/postgres
    volumes:
      - ../sql-data/game.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - "6000:5432"
    restart: always

volumes:
  postgres:
