version: '3.8'

services:
  back-end:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4001:8000
    networks:
      - leadernet

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: game
      PGDATA: /data/postgres
    volumes:
      - ../sql-data/game.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - "${PG_PORT}:5432"
    restart: always
    networks:
      - leadernet

volumes:
  postgres:

networks:
  leadernet:
    driver: bridge
