version: '3.8'
name: sql-training

services:
  back-end:
    build:
      context: ./sql-back
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - trainnet

  front-end:
    build:
      context: ./sql-front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5173:3000
    networks:
      - trainnet

  sqlserver:
    build: ./sql-server
    ports:
      - 5174:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    networks:
      - trainnet

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world
      PGDATA: /data/postgres
    volumes:
      - ./sql-data/postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - "5175:5432"
    restart: always
    networks:
      - trainnet

volumes:
  postgres:
  sqlserver_data:

networks:
  trainnet:
    driver: bridge
